<?php

namespace ContainerX6yKIUT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntityUpsertService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\EntityUpsert' shared autowired service.
     *
     * @return \App\Service\EntityUpsert
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/EntityUpsert.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Validator.php';

        return $container->privates['App\\Service\\EntityUpsert'] = new \App\Service\EntityUpsert(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), new \App\Service\Validator(($container->privates['validator'] ?? $container->load('getValidatorService'))), ($container->privates['App\\Service\\QueryHelper'] ?? $container->load('getQueryHelperService')));
    }
}
