<?php

namespace ContainerX6yKIUT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioSecurity_Csp_RuntimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'nelmio_security.csp.runtime' shared service.
     *
     * @return \Nelmio\SecurityBundle\Twig\CSPRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/security-bundle/src/Twig/CSPRuntime.php';

        return $container->privates['nelmio_security.csp.runtime'] = new \Nelmio\SecurityBundle\Twig\CSPRuntime(($container->privates['nelmio_security.csp_listener'] ?? $container->getNelmioSecurity_CspListenerService()));
    }
}
