<?php

namespace ContainerX6yKIUT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_Describers_ConfigService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'nelmio_api_doc.describers.config' shared service.
     *
     * @return \Nelmio\ApiDocBundle\Describer\ExternalDocDescriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/api-doc-bundle/Describer/DescriberInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/api-doc-bundle/Describer/ExternalDocDescriber.php';

        return $container->privates['nelmio_api_doc.describers.config'] = new \Nelmio\ApiDocBundle\Describer\ExternalDocDescriber(['info' => ['title' => 'REST API', 'description' => 'This is an awesome REST API!', 'version' => '1.0.0'], 'components' => ['schemas' => ['User' => ['type' => 'object', 'properties' => ['login' => ['type' => 'string'], 'password' => ['type' => 'string'], 'email' => ['type' => 'string'], 'firstname' => ['type' => 'string'], 'lastname' => ['type' => 'string']]]], 'securitySchemes' => ['Bearer' => ['type' => 'http', 'scheme' => 'bearer', 'bearerFormat' => 'JWT']]], 'security' => [0 => ['Bearer' => []]], 'paths' => ['/api/login' => ['post' => ['summary' => 'Log in', 'tags' => [0 => 'Authentication'], 'requestBody' => ['content' => ['application/json' => ['schema' => ['type' => 'object', 'required' => [0 => 'login', 1 => 'password'], 'properties' => ['login' => ['type' => 'string'], 'password' => ['type' => 'string']]]]]], 'responses' => [200 => ['description' => 'Successful login', 'content' => ['application/json' => ['schema' => ['type' => 'object', 'properties' => ['token' => ['type' => 'string']]]]]], 401 => ['description' => 'Invalid credentials', 'content' => ['application/json' => ['schema' => ['type' => 'object', 'properties' => ['error' => ['type' => 'string', 'example' => 'Invalid credentials']]]]]]]]]]]);
    }
}
