<?php

namespace ContainerX6yKIUT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQueryHelperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\QueryHelper' shared autowired service.
     *
     * @return \App\Service\QueryHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/QueryHelper.php';

        return $container->privates['App\\Service\\QueryHelper'] = new \App\Service\QueryHelper(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
