<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'register_user' => [[], ['_controller' => 'App\\Controller\\ApiRegistrationController::registration'], [], [['text', '/api/register']], [], [], []],
    'display_current_user' => [[], ['_controller' => 'App\\Controller\\UserController::currentUserInfo'], [], [['text', '/api/users']], [], [], []],
    'update_current_user' => [[], ['_controller' => 'App\\Controller\\UserController::updateUserInfo'], [], [['text', '/api/users']], [], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login']], [], [], []],
    'app.swagger_ui' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger_ui'], [], [['text', '/api/doc']], [], [], []],
    'app.swagger' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger'], [], [['text', '/api/doc.json']], [], [], []],
];
